#handlers

---
handlers:
-
    handler: bitfield
    url: https://bitfieldconsulting.com/golang
-
    handler: threedotslabs
    url: https://threedots.tech/
-
    handler: hashnode
    url: https://hashnode.com/n/go
-
    handler: appliedgo
    url: https://appliedgo.net
-
    handler: devto
    url: https://dev.to
-
    handler: golangorg
    url: https://tip.golang.org/blog/all
